### ISSUE TITLE
[BUG] setLoggerLevel don't work

### ISSUE THREAD

**Issue by felipedkalves** [googlecast/CastReceiver#10]
I am trying to disable the receiver logs but even running the following command it still displays the logs:

`cast.framework.CastReceiverContext.getInstance().setLoggerLevel(cast.framework.LoggerLevel.NONE);`

This started to happen after the update on September 9, 2019.

**Comment by anjaneesh** [comment]
Can you confirm if this still happens after the new release on Oct 7th?

**Comment by jtromo** [comment]
We are investigating this issue.

**Comment by jtromo** [comment]
We haven't been able to reproduce this issue. Please reopen if this is still happening.
