### ISSUE TITLE
cannot get tracks of cea608/708

### ISSUE THREAD

**Issue by kevinbol** [googlecast/CastReceiver#12]
hi, when I load a link which includes cea608/708 tracks, cast.framework.TextTracksManager.getTracks() cannot get the cea608/708 tracks. 
is there any else method to get cea608/708 tracks and activate it ?

test link: https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8

**Comment by kevinbol** [comment]
add test link: https://vm2.dashif.org/dash/vod/testpic_2s/cea608.mpd

**Comment by jtromo** [comment]
Please try to set loadMux on the `CastReceiverOptions` to true. This will force load a CEA608 parser for Shaka.

**Comment by vpunjabi** [comment]
Please reopen if this is still an issue.
