### ISSUE TITLE
custom shaka TextDisplayer interface

### ISSUE THREAD

**Issue by byWhish** [googlecast/CastReceiver#13]
Hi i'm using TTML subtitles image format. There is a way to implemet in the receiver my own TextDisplayer interface like in the issue below.

https://github.com/google/shaka-player/issues/2182

Thanks

**Comment by c0d3base** [comment]
CAF converts TTML to WebVTT. We do this because TTML has timing issues when rendering on the screen. We don't advice partners to build their own text UI.
