### ISSUE TITLE
Customised widevine request

### ISSUE THREAD

**Issue by maniland** [googlecast/CastReceiver#14]
We are a DRM provider and as part of our product we need to customise the Widevine request that is sent to the license server. We are seeing that the CAF framework encrypts the post request, as such the license server cannot decrypt the request.  We use a `token` based system, the `token` need to be added to the request body before being sent. The `POST` needs to be unencrypted in order for us to use the `KID` and `token` to server a license.

I am trying to use the `playbackConfig.licenseRequestHandler` to add the token and if I breakpoint there and take the request and fire it at our license servers using `Curl` it works. I am confident it is the framework/CDM encrypting the request, but we don't see this issue in Chrome. any help or suggestions would be happily received.

I have included our `licenseRequestHandler` function below

```
function licenseRequestHandler(request) {
        request.body = JSON.stringify({
            token: token,
            drm_info: Array.apply(null, new Uint8Array(request.content)),
            kid: kid
        });

        request.headers['Content-Type'] = 'application/json';
        return request;
    }
```

**Comment by c0d3base** [comment]
Is this still an issue? And if so, are you trying to do this with DASH or HLS?

**Comment by vpunjabi** [comment]
Please reopen if this is still an issue.
