### ISSUE TITLE
Migration for GameManager APIs?

### ISSUE THREAD

**Issue by Drakota** [googlecast/CastReceiver#15]
Hello everyone, I seem to be unfortunately late to the google-cast dev party and wanted to develop a simple casual game for the cast and after looking the reference docs I've seen that they have seem to deprecate the possibility to create games, which is a real shame honestly :/ APIs like the GameManager seemed to be totally awesome, but is now deprecated.
I've seen now that the current API (CAF) doesn't really have the same useful APIs I've seen from the previous v2 for games, so I'd like to know if they were a clear path to migrating to CAF for casual game development, because the official docs don't seem to say anything about this.

Maybe @jtromo has any light to shine on this?
Thank you very much

**Comment by JackTheHack** [comment]
What do you mean by deprecating possibility to create games?

**Comment by Drakota** [comment]
Well they are deprecating and removing useful APIs to create simple cast games that would have helped. It feels like they discourage the possibility of easily create cast games.

**Comment by JackTheHack** [comment]
Yes, introducing new API and then deprecating them is kind of weird.

Maybe they dont have the capacity to handle the load from the APIs or something.
I guess its possible to create similar API through websockets.

In some way its even better as it will easier to adapt the game to other SmartTV platforms like Tizen or LG.

**Comment by jtromo** [comment]
Hi, yes these APIs were deprecated and are no longer supported on CAF or for future libraries.
