### ISSUE TITLE
Queue loading fails with " The passed in queueData is not completely valid"

### ISSUE THREAD

**Issue by raestrada95** [googlecast/CastReceiver#19]
Hello 

**original case**: https://issuetracker.google.com/issues/162640292

Has taken a very long time to get to this point. I have a test case where queue loading fails with this error. I have no idea why as it was working in the past. This api is poorly documented.

It hangs and refuses to play

"cast_receiver_framework.js:114 [ 3.144s] [cast.receiver.MediaQueue] The passed in queueData is not completely valid: [object Object] "

https://dev.electroteque.org/chromecast/

> 
function addItem(index) {
             var mediaInfo = new chrome.cast.media.MediaInfo(
            mediaContents[index]['sources'][0], 'video/mp4');

            mediaInfo.metadata = new chrome.cast.media.GenericMediaMetadata();
            mediaInfo.metadata.metadataType = chrome.cast.media.MetadataType.GENERIC;
            mediaInfo.metadata.title = mediaContents[index]['title'];
            mediaInfo.metadata.images = [
                {'url': MEDIA_SOURCE_ROOT + mediaContents[index]['thumb']}];

            return mediaInfo;
        }

           

     /*   var request = new chrome.cast.media.LoadRequest(mediaInfo);
        castSession.loadMedia(request).then(
            this.playerHandler.loaded.bind(this.playerHandler),
            function (errorCode) {
                this.playerState = PLAYER_STATE.ERROR;
                console.log('Remote media load error: ' +
                    CastPlayer.getErrorMessage(errorCode));
            }.bind(this));*/

        

        const queueItems = [
            new chrome.cast.media.QueueItem(addItem(0)),
            new chrome.cast.media.QueueItem(addItem(1))
        ];

        console.log("items", queueItems);

        const request = new chrome.cast.media.QueueLoadRequest(queueItems);

        request.startIndex = 0;
        request.currentTime = 0;

        castSession.getSessionObj().queueLoad(request,  () => {
           // console.log(this.session.getMediaSession());
            console.log("queue loaded");
        }, (e) => {
            console.log("queue load error");
        });
> 
<img width="605" alt="Capture" src="https://user-images.githubusercontent.com/34411704/90301381-c3b50780-de5c-11ea-9aad-cca2db5a6b71.PNG">

I'm being hassled about queue loading completely broken. Can't figure out what has changed. Any ideas ?

everything I try fails. It seems to try to load the clip but getting a decode error ?

>  [  4.183s] [cast.receiver.MediaQueue] The passed in queueData is not completely valid: [object Object] 
Fg @ cast_receiver_framework.js:114
cast_receiver_framework.js:114  [  4.211s] [cast.framework.common.EventHandler] onEvent for load 
cast_receiver_framework.js:114  [  4.386s] [cast.receiver.MediaManager] No need to prefetch more for now. 
cast_receiver_framework.js:114  [  4.404s] [cast.framework.PlayerManager] MediaManagerLoad 
cast_receiver_framework.js:114  [  4.647s] [cast.framework.media.SimplePlayer] loadContent: autoplay = true, initial_time = 9.31929 
cast_receiver_framework.js:114  [  4.676s] [cast.receiver.CastReceiverManager] Dispatching system volume changed event [1, false] 
receiver.html:127 Received Metadata  Pq
cast_receiver_framework.js:114  [  8.267s] [cast.framework.media.Player] Setting startAbsoluteTime null 
cast_receiver_framework.js:114  [  8.270s] [cast.receiver.MediaManager] Metadata loaded 
receiver.html:118 Media Loaded  Vq
receiver.html:151 Media Error  Nq
cast_receiver_framework.js:114  [  8.557s] [cast.receiver.MediaManager] Sending error message to *:* 
cast_receiver_framework.js:114  [  8.579s] [cast.framework.media.Player] player event: error 
cast_receiver_framework.js:114  [  8.582s] [cast.receiver.MediaManager] Sending error message to *:* 
cast_receiver_framework.js:114  [  8.616s] [cast.receiver.MediaManager] After 1 jump, transition is: QUEUE_ACTIVE 
cast_receiver_framework.js:114  [  8.621s] [cast.receiver.MediaManager] Dispatching MediaManager load event 
cast_receiver_framework.js:114  [  8.624s] [cast.receiver.MediaManager] Load message received:{"type":"LOAD","requestId":0,"mediaSessionId":1,"media":{"contentId":"//videos.electroteque.org/bitrate/elephants_dream_600k.mp4","streamType":"BUFFERED","contentType":"video/mp4","metadata":{"type":0,"metadataType":0,"title":"Elephants Dream","subtitle":"Subtitle","images":[{"url":"//static.electroteque.org/images/stills/ed_still.jpg"}],"activeTextId":-1,"defaultDolbyAudioIndex":-1},"textTrackStyle":{"foregroundColor":"#FFFFFFFF","backgroundColor":"#FFFFFF00"},"customData":{}},"autoplay":true,"currentTime":0} 
cast_receiver_framework.js:114  [  8.645s] [cast.framework.common.EventHandler] onEvent for load 
cast_receiver_framework.js:114  [  8.737s] [cast.receiver.MediaManager] No need to prefetch more for now. 
cast_receiver_framework.js:114  [  8.749s] [cast.framework.PlayerManager] MediaManagerLoad 
cast_receiver_framework.js:114  [  8.756s] [cast.framework.media.Player] endInternal() 
cast_receiver_framework.js:114  [  8.865s] [cast.framework.media.EmbeddedPlayer] ended 
receiver.html:142 Media Finished  Tq
cast_receiver_framework.js:114  [  8.960s] [cast.framework.media.SimplePlayer] loadContent: autoplay = true, initial_time = 0 
receiver.html:127 Received Metadata  Pq {type: "LOADED_METADATA", currentMediaTime: 0}
cast_receiver_framework.js:114  [ 14.784s] [cast.framework.media.Player] Setting startAbsoluteTime null 
cast_receiver_framework.js:114  [ 14.805s] [cast.receiver.MediaManager] Metadata loaded 
receiver.html:118 Media Loaded  Vq {type: "PLAYER_LOAD_COMPLETE", media: {…}}
receiver.html:151 Media Error  Nq {type: "ERROR", detailedErrorCode: 102, reason: undefined, error: undefined}
cast_receiver_framework.js:114  [ 15.322s] [cast.receiver.MediaManager] Sending error message to *:* 
cast_receiver_framework.js:114  [ 15.392s] [cast.framework.media.Player] player event: error 
cast_receiver_framework.js:114  [ 15.403s] [cast.receiver.MediaManager] Sending error message to *:* 
cast_receiver_framework.js:114  [ 15.467s] [cast.framework.media.Player] reset() 
cast_receiver_framework.js:114  [ 15.497s] [cast.framework.media.Player] endInternal() 
cast_receiver_framework.js:114  [ 15.924s] [cast.framework.media.EmbeddedPlayer] ended 
receiver.html:142 Media Finished  Tq {type: "MEDIA_FINISHED", currentMediaTime: 0, endedReason: "ERROR"}

**Comment by gomez-andres** [comment]
If you are still facing this issue please re-open the original bug that you filed via the issue tracker (https://issuetracker.google.com/issues/162640292) and we'll take a closer look.
