### ISSUE TITLE
Having some problems following the instructions to get the receiver working.

### ISSUE THREAD

**Issue by computamike** [googlecast/CastReceiver#20]
I have been following the instructions in the README.md file - 

I got to point 5 - 
_Using the Chromecast setup application, make sure [x] send your serial number to Google is checked. This is the only way that you can access your unpublished receiver_

I can't find that option on the Google Home app - but equally, I'm not sure what the [x] signifies - does that mean that this is not longer required?

I carried on with the instructions.
Step 7 says : 
_Enter the App ID of your receiver application into your sender application or one of our sample sender applications listed above._

there are no sample sender applications listed above.  Clicking on the link to https://developers.google.com/cast/docs/sample-apps (am I missing something?)

**Comment by jtromo** [comment]
Thanks for the report. The README has been updated to be hopefully more clear and up to date.

As for the sample sender apps, all of the samples listed that do not say "receiver" are samples that can be used for testing:

https://developers.google.com/cast/docs/sample_apps#reference_apps
