### ISSUE TITLE
Chromecast receiver with custom header

### ISSUE THREAD

**Issue by fridapinto-debug** [googlecast/CastReceiver#23]
Hello I have created the chromecast receiver correctly and I can cast dash , mp4 and hls videos correctly. I also implemented drm license request using licenserequesthandler.

I want to know how can I add custom headers to manifestrequest and segment request? I want to check specific headers for media to be streamed like custom User-Agent, adding extra header.

so far I have done:

```
playbackConfig.manifestRequestHandler = requestInfo => {

 // requestInfo.withCredentials = true;
  requestInfo.headers['User-Agent'] = 'Mozilla 6.0 firefox';
  
  
   };
```

**Comment by jjfster** [comment]
fridapinto-debug,

Did you ever get this working?

**Comment by fridapinto-debug** [comment]
these donot change the request headers. Have to try different approach

**Comment by gomez-andres** [comment]
The code sample provided is setting a property on a null object. You can try modifying your code to first create the header object and set its properties.
```
playbackConfig.manifestRequestHandler = requestInfo => {
  requestInfo.headers = {};
  requestInfo.headers['User-Agent'] = 'Mozilla 6.0 firefox';
   };
```

Do note that overriding the user agent may not be supported. If you are still experiencing issues please open a bug in the issue tracker: https://issuetracker.google.com/issues/new?component=190205&template=814901
