### ISSUE TITLE
Behavior when stop Cast on android with Android TV receiver.

### ISSUE THREAD

**Issue by namtran-cc** [googlecast/CastReceiver#24]
Currently, we implement chromecast on Android TV receiver. We have an issue bellow need you confirm: When use android 11 device cast to android TV receiver after that we disconnect cast on android 11 device then android TV receiver force to home (it is different with android under 11 devices. On android under 11 when disconnect on it then app on android TV receiver still playing). So we need confirm behavior when disconnect Cast on android device is force app to home or app still playing. Please help us confirm on it.

Thanks and regards, 
Nam

**Comment by namtran-cc** [comment]
Could you please help me check it.

Thank you,

**Comment by jtromo** [comment]
Thanks for raising the issue. Please file an issue with the [Cast SDK Issue Tracker](https://developers.google.com/cast/support#report_issues) with your setup and steps to reproduce the issue.
