### ISSUE TITLE
Example not working, websocket failed

### ISSUE THREAD

**Issue by mladenp** [googlecast/CastReceiver#25]
Receiver code doesn't work, there is an issue with debugger and  `'is_device_registered' of null error`. 
Disabling debugger fails with websocket error:
`WebSocket connection to 'ws://localhost:8008/v2/ipc' failed: `

**Comment by jtromo** [comment]
Can you provide some steps to reproduce the issue and provide the receiver ID that you are using?

Have you registered your devices in the [Cast SDK Developer Console](https://cast.google.com/publish/#/overview)?

**Comment by mladenp** [comment]
The issue was that i tried to run receiver locally, once i deployed it and pointed custom receiver to that url everything was workoing correctly.
