### ISSUE TITLE
Http authorization header isn't working 

### ISSUE THREAD

**Issue by playtvgo** [googlecast/CastReceiver#26]
I am trying to create a receiver which can play hls / dash media with http authorization header 
In the receiver.js I have done like this 
```js
    var header_now = {}
    if (customData.user_agent) {
        header_now['User-Agent'] = customData.user_agent
    }
    if (customData.origin) {
        header_now['Origin'] = customData.origin
    }
    if (customData.token) {
        header_now['Token'] = customData.token
    }
    if (customData.referer) {
        header_now['Referer'] = customData.referer
    }
    console.log("header " + header_now);

    playbackConfig.licenseRequestHandler = requestInfo => {
        if (header_now)
            requestInfo.headers = header_now;
        if (typeof customData.withCredentials === 'boolean') {
            requestInfo.withCredentials = customData.withCredentials;
        }
    };
    playbackConfig.manifestRequestHandler = requestInfo => {
        if (header_now)
            requestInfo.headers = header_now;
        if (typeof customData.withCredentials === 'boolean') {
            requestInfo.withCredentials = customData.withCredentials;
        }
    };
    playbackConfig.segmentRequestHandler = requestInfo => {
        if (header_now)
            requestInfo.headers = header_now;
        if (typeof customData.withCredentials === 'boolean') {
            requestInfo.withCredentials = customData.withCredentials;
        }
    };
```
but it's giving me `3116403 ` error , how to fix this

**Comment by jtromo** [comment]
Per the [error codes document](https://developers.google.com/cast/docs/web_receiver/error_codes), a 3116403 error "means that the manifest request is successfully made but the server refuses to serve it. This could be CORS, auth, or any other server or integration issues that developers should look at."

I would recommend inspecting your receiver session to see if you see any other errors or network failures that might provide more insight into what's happening with your receiver.

**Comment by vpunjabi** [comment]
Please reopen if this is still an issue.

**Comment by ghost** [comment]
Hi,
I'm trying to add the User-Agent header, and I've tried your solution but, even if inside logs I can see the correct user agent, I still receive a request with a different user agent. Do you have an idea why?

**Comment by huythao99** [comment]
@playtvgo Could you show your receiver.js file, where you call playbackConfig.licenseRequestHandler in your file?
