### ISSUE TITLE
How to make video loop on Custom Cast Receiver

### ISSUE THREAD

**Issue by rajBopche** [googlecast/CastReceiver#27]
On the custom cast receiver, I'm able to play videos successfully. However, once the video ends, the player goes to the IDLE state and shows the default home screen. **What I want is to make the same video loop continuously**. How to make this happen?

My Index.html
```html
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="css/receiver.css" media="screen" />
  <script src="//www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js"></script>
  <!-- Cast Debug Logger -->
  <script src="//www.gstatic.com/cast/sdk/libs/devtools/debug_layer/caf_receiver_logger.js"></script>
</head>

<body>
  <cast-media-player></cast-media-player>
    <script src="js/receiver.js" type="module"></script>
  </footer>
</body>

</html>
```

This is how I build my media Request
```js
function buildMediaRequest(exerciseData) {
  const loadRequestData = new cast.framework.messages.LoadRequestData();
  loadRequestData.media = new cast.framework.messages.MediaInformation();
  const metadata = new cast.framework.messages.GenericMediaMetadata();
  metadata.title = exerciseData.exerciseWrap.exercise.name;
  metadata.images = exerciseData.exerciseWrap.exercise.thumbnail;
  loadRequestData.media.contentUrl = exerciseData.exerciseWrap.exercise.media[0].url;
  loadRequestData.media.contentType = 'video/mp4';
  loadRequestData.media.metadata = metadata;
  return loadRequestData;
}
```

And this is how I play the media
```js
const context = cast.framework.CastReceiverContext.getInstance();
const playerManager = context.getPlayerManager();
...
function playVideo(mediaRequest) {
  playerManager.load(mediaRequest)
    .then(function () {
      playerManager.play();
    });
}
```

**<h3>How can I make the same video play continuously once it ends ?<h3>**

**Comment by vpunjabi** [comment]
You can create a queue and have the same item be returned to create a loop. You can refer to the queue documentation here: https://developers.google.com/cast/docs/web_receiver/queueing

**Comment by rajBopche** [comment]
> You can create a queue and have the same item be returned to create a loop. You can refer to the queue documentation here: https://developers.google.com/cast/docs/web_receiver/queueing

Yup, I ended up using the same. Although was a much more hassle. What a drag? - _ -
