### ISSUE TITLE
Local network HTTP media stream no longer functional

### ISSUE THREAD

**Issue by adriancable** [googlecast/CastReceiver#28]
It isn't uncommon for people to have media servers where there is a published Cast receiver app which plays an audio stream from a local network URL, e.g. http://10.0.0.6:1234/stream.mp3. (I am the developer of one such device.)

Until a few days ago this worked. Now (since a recent Cast firmware update) it does not. Looking in the Chrome debug console, the issue is that, even though loadRequestData.media.contentUrl is correct (e.g. 'http://10.0.0.6:1234/stream.mp3'), the actual request coming from the Cast device is the same but HTTPS (e.g. 'http**s**://10.0.0.6:1234/stream.mp3'). So the media server's HTTP server sees an incoming connection and instead of seeing GET /stream.mp3 HTTP/1.1 in plaintext it sees a binary SSL handshake and goes crazy.

There doesn't appear to be any sensible way around this. 'Fixing' the media server to run an HTTPS server instead of HTTP, the Cast request still fails because now there's a self-signed cert.

Is this a deliberate 'break' or an accident, and in either case how do I proceed? Thank you!

_Edit: this still works fine when casting to the default media receiver. It only breaks for custom receivers. Is there some new setting (not documented?) I need to set in the custom receiver to allow this?_

**Comment by vpunjabi** [comment]
Which Cast firmware version is the above issue occurring? Which version was it working on? We tried to reproduce the issue but were not successful. Any additional steps to reproduce would be helpful.

**Comment by gomez-andres** [comment]
Closing this bug due to inactivity. This repository tracks bug with the sample receiver app. To better address your issue please file a bug in the cast issue tracker https://cast.google.com/publish/#/support .
