### ISSUE TITLE
VMAP/Vast has a fixed wrapper limit (that is too small)

### ISSUE THREAD

**Issue by EyMaddis** [googlecast/CastReceiver#31]
I am currently integrating ads into a cast receiver app via Google Ad Managers VMAP support.
Unfortunately, I noticed that it basically does not work for us for 99% of the time.

After digging around and enabling the debug mode I noticed the following:

```
[cast.framework.breaks.vast.VastManager] Fail to load VAST ads. Error: Number of redirects exceeded the set limit. 
```
I enabled the logger for this:
```
cast.debug.CastDebugLogger.getInstance().loggerLevelByTags = {
        "cast.framework.breaks.vast.VastManager": cast.framework.LoggerLevel.DEBUG,
    };
```

I then tried to find a way to configure this limit some where but noticed that the number is a constant in the code. (Screenshot via Chrome Dev Tools).

![image](https://user-images.githubusercontent.com/1409100/148262064-3a394a7b-dee5-43e6-a28f-a7c2700f0f5e.png)

This is currently blocking the usage of the ad provider smartclip, a very large ad provider in Germany.
I would like to have a way to increase that number. 

I can provide an ad call if necessary, privately would be appreciated.

I also created an issue [here](https://issuetracker.google.com/issues/213266825), because I was unsure where it belongs.

**Comment by gomez-andres** [comment]
Thank you for your feedback. This repository tracks bugs with the sample receiver app. Since you have filed a bug in the issue tracker we will continue the investigation there. Closing this issue.

**Comment by philipperoy1** [comment]
@EyMaddis Did you end up finding a solution for this ? I have the same issue right now.

**Comment by EyMaddis** [comment]
I opened a ticket over at Google, made sure to say how important that is and long story short my customer dropped Chromecast support :/

**Comment by philipperoy1** [comment]
@EyMaddis Yeah I saw your ticket, that's what led me here. I feel really blocked by this issue.
Did you found any possible workaround ?

**Comment by gomez-andres** [comment]
Hi Philip, if you are finding that this is still an issue, let us know in the public facing issuetracker ticket so that our team can be notified and re-open the investigation.

https://issuetracker.google.com/213266825 [CAF Receiver] Cast Receiver has a fixed VAST wrapper limit (that is too small)
