### ISSUE TITLE
--playback-logo-image not working...

### ISSUE THREAD

**Issue by sinewave440hz** [googlecast/CastReceiver#33]
Hi,  I have set up the CastReceiver and published it to surge. It is showing correctly when using the web sender project, apart from this issue - the playback-logo-image is not showing up on the while playing on the device. I've tried using the same image as a watermark in the css file and it shows correctly then. Any ideas?

Cast firmware version: 1.56.275994

**Comment by gomez-andres** [comment]
Alan, this repository tracks bug with the sample receiver app. To better address your issue please file a bug in the cast issue tracker https://cast.google.com/publish/#/support . Ensure that you are following all of the steps provided in the [styling guide](https://developers.google.com/cast/docs/web_receiver/customize_ui#playback_logo). If you are still having issues please do file a bug.
