### ISSUE TITLE
Cast receiver unable to play video url having redirection

### ISSUE THREAD

**Issue by rajBopche** [googlecast/CastReceiver#34]
We have developed a Custom Cast Receiver (registered on Cast Console)

The cast receiver smoothly plays a video whose URL does not have any redirection. 
However, if the video URL contains a redirection, the cast receiver fails with a `311` error.

I'm posting the curl responses for both types of videos URL

Type 1: Video URL **without**  any redirection _(this **video plays** on the receiver)_

<img width="912" alt="Screenshot 2022-01-27 at 6 13 55 PM" src="https://user-images.githubusercontent.com/42612104/151361224-ed58d105-c8e5-4726-8eca-e57d4d9b26ce.png">

Type 2: Video URL **with** redirection _(this **video does not play** on the receiver)_

<img width="972" alt="Screenshot 2022-01-27 at 6 15 06 PM" src="https://user-images.githubusercontent.com/42612104/151361409-e3688fdd-3637-45e0-a66d-980eae0d1a8a.png">

Also posting the error-response from cast receiver

<img width="257" alt="Screenshot 2022-01-27 at 6 19 28 PM" src="https://user-images.githubusercontent.com/42612104/151362060-1cc02e69-31f2-4988-be55-314fc9f56230.png">

Looks like, the custom receiver is unable to handle URL redirection. Any way to enable redirection?

**Comment by rajBopche** [comment]
@jtromo @c0d3base @stefanovualto @gomez-andres guys I'm kinda lost here, any tips, reference, guidance would truly help🙏🏻

**Comment by gomez-andres** [comment]
@rajBopche This repository tracks bug with the sample receiver app. To better address your issue please file a bug in the cast issue tracker https://cast.google.com/publish/#/support . Please include any test assets and ensure that they are accessible publicly. For what it's worth, I tried loading the url provided and am getting 403 permission denied errors.
