### ISSUE TITLE
Is there suggested Web Receiver code for speaker application

### ISSUE THREAD

**Issue by choruschuang** [googlecast/CastReceiver#35]
Hi,

We'd like to implement this in a speaker. Is there a suggested Web Receiver code for speaker application.

**Comment by gomez-andres** [comment]
Hello, thank you for your interest in integrating with the cast ecosystem. By default cast receivers support audio only playback. No special considerations are needed when developing the receiver application with regards to audio only content. Please see the overview guide for how to create your first cast receiver here: https://developers.google.com/cast/docs/web_receiver/basic . Also be sure to check out the  cast receiver codelab here: https://developers.google.com/cast/codelabs . If you want your receiver app to be castable to audio only devices ensure that you check the `Supports casting to audio-only devices` box during the registration process as mentioned here: https://developers.google.com/cast/docs/registration#register_your_application

**Comment by gomez-andres** [comment]
Please reopen the issue if you need more assistance.
