### ISSUE TITLE
Handling multiple senders in web receiver

### ISSUE THREAD

**Issue by SashiWork** [googlecast/CastReceiver#37]
Hi Team,

I'm trying a find a solution where multiple senders should not be connected to a receiver.

If a receiver is already connect to a sender and another sender tries to connect, it should disconnect the previous connected sender and connect to the new sender.

Please let me know, how it can be done?

**Comment by joeyparrish** [comment]
Does this help?

https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.CastReceiverContext#getSenders

**Comment by SashiWork** [comment]
I have used the getSenders method and it returns empty array and the getSender return null
Below is the sample code.

`const context = cast.framework.CastReceiverContext.getInstance();
const playerManager = context.getPlayerManager();
let senders = context.getSenders();
let sender = context.getSender();
//let senders = cast.framework.CastReceiverContext.getSenders();
//let senders = cast.framework.system.Sender.getSenders();

let aesToken;

// Debug Logger
const castDebugLogger = cast.debug.CastDebugLogger.getInstance();
const LOG_TAG = 'MyAPP.LOG';

// Enable debug logger and show a 'DEBUG MODE' overlay at top left corner.
castDebugLogger.setEnabled(true);

// Show debug overlay
castDebugLogger.showDebugLogs(true);

// Set verbosity level for Core events.
castDebugLogger.loggerLevelByEvents = {
  'cast.framework.events.category.CORE': cast.framework.LoggerLevel.INFO,
  'cast.framework.events.EventType.MEDIA_STATUS': cast.framework.LoggerLevel.DEBUG
}

// Set verbosity level for custom tags.
castDebugLogger.loggerLevelByTags = {
  LOG_TAG: cast.framework.LoggerLevel.DEBUG,
};



playerManager.setMessageInterceptor(
  cast.framework.messages.MessageType.LOAD,
  request => {    
    // castDebugLogger.info(LOG_TAG, ' senderID ' + JSON.stringify(senders));
    // castDebugLogger.info(LOG_TAG, ' sender ' + JSON.stringify(sender));
    // // Map contentId to entity
    if (request.media && request.media.entity) {
      
      request.media.contentId = request.media.entity;
    }

    return new Promise((resolve, reject) => {      
      aesToken = request.media.customData.token;      
      // Fetch repository metadata            
      request.media.hlsSegmentFormat = cast.framework.messages.HlsSegmentFormat.TS;
      castDebugLogger.info(LOG_TAG, ' senderID ' + JSON.stringify(context.getSenders()));
    castDebugLogger.info(LOG_TAG, ' sender ' + JSON.stringify(sender));
      resolve(request);
    });
  });

const playbackConfig = new cast.framework.PlaybackConfig();

playbackConfig.licenseRequestHandler = requestInfo => {
  requestInfo.withCredentials = false;
  requestInfo.headers = {};
  requestInfo.headers['Authorization'] = 'Bearer ' + aesToken;  
};

context.start({
  playbackConfig: playbackConfig
}
);`

Can you please guide in using it properly where it returns the value.

**Comment by joeyparrish** [comment]
The `getSender()` call is definitely wrong.  getSender requires a sender ID as an argument.

I don't see anything wrong with the `getSenders()` call, but it's not clear **when** it's called:

```js
let senders = context.getSenders();
```

At load-time, I would expect you not to have any senders connected.  Have you tried listening for the sender connect and/or disconnect events, then calling getSenders()?

```js
context.addEventListener('senderconnect', (event) => {
  console.log('New sender ID:', event.senderId);
  console.log('All sender IDs:', context.getSenders().map(s => s.id));
});
```

https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.system.SenderConnectedEvent
https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.system.Sender
https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.CastReceiverContext#getSenders

**Comment by SashiWork** [comment]
Hi,

Can you please suggest me a way where only one sender can be connected to the receiver, and when other tries to connect to receiver the previous session should end.

I tried by ending session on the current sender but it ends the whole session and two devices get disconnected.

code from sender for disconnection
```
 castSession!!.setMessageReceivedCallbacks("urn:x-cast:com.example.test"
        ) { castDevice, namespace, message ->
            Log.v("CHROME_CAST", message)
            castContext?.sessionManager?.endCurrentSession(true)
        }
```

code from receiver to send message to sender
```
context.addEventListener(cast.framework.system.EventType.SENDER_CONNECTED, (event) => {
  let senders;
  senders = context.getSenders();
  if(senders && senders.length > 1){
    context.sendCustomMessage(nspace, senders[0]?.id, 'dissconnect');
  }
});
```

If there is any other way or method to keep only one sender connected to the receiver, please let me know.

**Comment by joeyparrish** [comment]
Actually, I'm not aware of a way for a sender to disconnect without a user interaction.  In my experience, you would normally trigger the Chrome dialog that lets the user then click to disconnect.

**Comment by vpunjabi** [comment]
Per the guideline a sender shouldn't disconnect on connection of another sender. So this is working as intended. You can view the guidelines on the developer site:
https://developers.google.com/cast/docs/design_checklist/sender#sender-control-end
