### ISSUE TITLE
[Cast Docs] Codelab - ngrok instructions

### ISSUE THREAD

**Issue by caseysoftware** [googlecast/CastReceiver#38]
Getting started with ngrok has four steps:

1. start your service
2. create an ngrok account
3. Install the authtoken to connect the local agent to your account
4. Then start the tunnel as described

Currently, the guide leaves out steps 2 & 3.

Ref: https://ngrok.com/docs/getting-started

**Comment by vpunjabi** [comment]
Thank you, we will update it

**Comment by jtromo** [comment]
This has been fixed.
