### ISSUE TITLE
Built In TV chromecast not being recognized

### ISSUE THREAD

**Issue by guibirk** [googlecast/CastReceiver#39]
I have an Android sender app that is working fine with a Web Receiver, using the chromecast device connected to the TV.
But I also have a TV with a built in chromecast that is not being recognized by the sender app. Apparently only YouTube and Netflix are able to discover the built in chromecast. 
Do I need an Android TV application to be able to discover the TV built in chromecast?

**Comment by vpunjabi** [comment]
No. Are you to reproduce the issue with the sample Android sender app? Can you follow the directions on the [Cast developer site](https://developers.google.com/cast/docs/get-started?hl=en) and report back if you run into any issues.
