### ISSUE TITLE
Cactool not working - cast button not shown

### ISSUE THREAD

**Issue by tommyzat** [googlecast/CastReceiver#41]
I'm trying to use Cactool however pressing the "Set app ID" button only refreshes the page and nothing is changed.

https://casttool.appspot.com/cactool/?appId=CC1AD845

The cast button does not appear at all.

**Comment by Alvey-005** [comment]
You need to connect your cast device and laptop to the same network and if the app is not published yet you need to register the device in the chrome cast console to get the cast icon in the CAC tool. You can check it by setting the app id to the default app id if the button is showing.
