### ISSUE TITLE
Add Custom Header 

### ISSUE THREAD

**Issue by Alvey-005** [googlecast/CastReceiver#42]
I am developing a custom receiver app for an ott platform where we need to send an authorization token as a request header for decrypting our content. Can anyone help me with how I can add the custom header for hls content?

**Comment by Rayraz** [comment]
I'm running into the same issue. Did you find any solution yet?

**Comment by Alvey-005** [comment]
Need to give the authorization token in request header like this 
`context.getPlayerManager().setMediaPlaybackInfoHandler((loadRequest, playbackConfig) => {
                 playbackConfig.licenseRequestHandler = requestInfo => {
                             requestInfo.withCredentials = false;
                             requestInfo.headers = {...requestInfo.headers,'Authorization' : loadRequest.customData.token }
                  };
                return playbackConfig;
});`
you can pass the Authorization token in customData field

**Comment by ghost** [comment]
Hi,
I'm trying to add the User-Agent header, and I've tried this [solution](https://github.com/googlecast/CastReceiver/issues/26), even if inside logs I can see the correct user agent, I still receive a request with a different user agent. Do you have an idea why?

**Comment by huythao99** [comment]
Did you find any solution yet?
