### ISSUE TITLE
ENH: Chromecast Receiver API (?): "Like API"

### ISSUE THREAD

**Issue by westurner** [googlecast/CastReceiver#44]
As a Chromecast and Google Home and Google Assistant User, I would like to "Like" the currently playing media track in a standard way.

- Is there a already pan-chromecast-service API to 'Like'?
- These prompts currently work w/ Google Assistant on {YT, YT Music,} (2022) :
  - "Like this"
  - "Like this track"
  - Is there an easier way to IDK `curl` text messages to GAssistant aPI?
    - https://github.com/endoplasmic/google-assistant
- "Like API": ~ {url}/.well-known/actions/like
  - https://schema.org/LikeAction
  - `?action=LikeAction&`
  - [ ] ENH,SCH: Create the JSON-LD for a W3C Web Annotation at the timecode at the url
    - https://www.w3.org/TR/annotation-model/#fragment-selector
    - https://www.w3.org/TR/media-frags/#general-structure
    - https://www.w3.org/TR/media-frags/#media-fragment-webapps
      - [ ] ENH,SCH: YouTube: Is youtube's `?t=1h1m1s` Media Fragment compatible so that W3C Web Annotations work with the timecode?

Use cases:
- Make 'Hey Google "Like this"' also work with Di.fm and SoundCloud, for example
- https://github.com/skorokithakis/catt/issues/415

**Comment by vpunjabi** [comment]
This seems like it is related to the assistant. Can you please file a bug related with the assistant team. If you still feel this is cast related, can you please file an issue using the instructions provided on the support page https://developers.google.com/cast/support#report_issues

**Comment by westurner** [comment]
This is not completed.

This is not possible without Google Cast adding an API that Cast apps can implement to support "Hey Google "Like this"" for additional services beyond YouTube Music.
