### ISSUE TITLE
HLS freeze and authomatic shutdown

### ISSUE THREAD

**Issue by JESUMH** [googlecast/CastReceiver#45]
Hi,

**ISSUE**
I'm trying to load a live stream playlist in HLS format but custom receiver is not working. Video is freezing in random moments during any time. After 20 minutes or 30 minutes, chromecast leave session and shutdown it.

**MEDIA FORMAT**
We are using HLS v3 and HLS v4 version.

**FIXES**
We try to fix it with HLSSegmentFromat TS or AAC and StreamType LIVE. This configuration is not working.  

Have you any idea about what is the problem?

Thank you,
Jesús Martínez

**Comment by vpunjabi** [comment]
Can you please open ticket by following the instructions for the issue tracker https://developers.google.com/cast/support#report_issues

Also please include additional information such as device type, stream used, repro steps, ...

**Comment by JESUMH** [comment]
Hello,

We found the problem when we was setting HLS segment format In TS. We removed this configuration and we only setted AAC segment format with one type of stream.

Also, devices crashed when timeshift had 20 hours.

Thank you for all,
Jesus Martinez
