### ISSUE TITLE
BreakClip mime-type "application/x-mpegURL" error

### ISSUE THREAD

**Issue by kaderdib** [googlecast/CastReceiver#46]
Hello,

I am getting this error when i am trying to add Ad Breaks a VMAP Ad URL.
I tested with the doubleclick ad server.
When the VAST INLINE reponse from the ad server provides a MediaFile withe the mime-type "application/x-mpeg**URL**", the Cast SDK throws and error 104.
Find below some logs :

_app.js:1433 MediaCast.onPlayerLoadComplete
app.js:1433 sendStreamInformation: {"version":1,"action":"stream_information","duration":2108}
cast_receiver_framework.js:116  [  6.103s] [cast.framework.media.util] cannot guess mime type from given contenId/Type. Assume that this is video/mp4 
th @ cast_receiver_framework.js:116
2app.js:1433 Media Manager MEDIA STATUS
app.js:1433 MediaCast.onLoadStart
app.js:1433 MediaCast.setState LOAD
app.js:454 ---> STATE :: LOAD
app.js:1433 MediaCast.isMediaState
app.js:1433 MediaCast.clearTimerState
cast_receiver_framework.js:116  [  6.219s] [StitchingPlayer] player event: break clip error 
cast_receiver_framework.js:116  [  6.224s] [cast.receiver.MediaManager] Sending error message to *:* 
app.js:1433 Media Manager ERROR: {"type":"ERROR","detailedErrorCode":104}
app.js:1433 MediaCast.onError_

It seems to be case sensitive issue. When i try with an other static URL where i can change the type to "application/x-mpeg**url**", it works.
In SDK Cast, i do not find an api to set the list of accepted mime-types.

Have someone already experienced this error ?

**Comment by joeyparrish** [comment]
Thanks for the report.  This has been fixed internally, and the fix should be in the next Cast Receiver SDK release.  We do not have an ETA for that release at this time.
