### ISSUE TITLE
HLS Videos not working 

### ISSUE THREAD

**Issue by ShaimaaHamdan** [googlecast/CastReceiver#5]
Hello , I use this sample to run the following urls through chrom cast device 
https://cdn.laliga.es/vod/mp4:2019-02-24_15-58-47_res-fem-bet-bar-3min.mp4/playlist.m3u8
https://cdn.laliga.es/vod/mp4:2018-06-03_17-31-07_5pfosyogkb8_sbr_ttmrsqxkayt.mp4/playlist.m3u8 
https://6954a71498174453877a15012532b59c.azureedge.net/085b9f90-988a-42be-82ee-b2961df81c23/62f9b6f9-8221-4644-b198-9f9f718e881f.ism/manifest(format=m3u8-aapl)

always i got the same error as follow :
![image](https://user-images.githubusercontent.com/8478773/54830538-f7681e00-4cb8-11e9-96c4-13f6a1cd3d3f.png)

my videos doesn't require any license . can you please help me in that ?

**Comment by anjaneesh** [comment]
Hello , i am able to play https://cdn.laliga.es/vod/mp4:2019-02-24_15-58-47_res-fem-bet-bar-3min.mp4/playlist.m3u8 using default CAF receiver with out any issue other than some buffering. Can you share your code snippet for load request please.

**Comment by ShaimaaHamdan** [comment]
Hello , now i am using this repo as sender ( i didn't change anything inside the code )  and for casting videos i used this repo
https://github.com/googlecast/CastVideos-chrome
i was testing the three url again the first two are working fine but the third one not working at all 
https://6954a71498174453877a15012532b59c.azureedge.net/085b9f90-988a-42be-82ee-b2961df81c23/62f9b6f9-8221-4644-b198-9f9f718e881f.ism/manifest(format=m3u8-aapl)

so can you tell me what is the wrong with this video ?

**Comment by jtromo** [comment]
Please make sure that you are setting the appropriate content types and segment formats (https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages#.HlsSegmentFormat and https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.messages#.HlsVideoSegmentFormat).

The 104 error indicates an issue with the data segment: https://developers.google.com/cast/docs/web_receiver/error_codes

Reopen if you continue to have issues.
