### ISSUE TITLE
How to build castReceiver into your own device without google cast device

### ISSUE THREAD

**Issue by y330388094** [googlecast/CastReceiver#60]
不使用google cast device设备的情况下，怎么将castReceiver集成到自己的设备上面，并与发送器进行通信，即在自己的设备上内置一个googlecast

**Comment by joeyparrish** [comment]
This repository contains a sample receiver application, which is just a web page the device loads when requested.  The receiver app must be registered with Cast and given an app ID, and the device must have the necessary firmware to respond to Cast commands and display apps by ID.

I don't believe there's anything here that does what you're asking for, but I hope that description of the tech stack is helpful!

**Comment by y330388094** [comment]
> This repository contains a sample receiver application, which is just a web page the device loads when requested. The receiver app must be registered with Cast and given an app ID, and the device must have the necessary firmware to respond to Cast commands and display apps by ID.
> 
> I don't believe there's anything here that does what you're asking for, but I hope that description of the tech stack is helpful!

我看过google cast的官方资料，如果使用默认web接收器是不需要进行注册的，现在我想用默认的web接收器，然后运行在我自己的设备上而不是google cast的设备，这里的固件需要怎么做，有什么参考资料吗？

**Comment by joeyparrish** [comment]
Translated via Google Translate:

> I have read the official information of Google Cast. If you use the default web receiver, there is no need to register. Now I want to use the default web receiver and run it on my own device instead of the Google Cast device. What do I need to do with the firmware here? Are there any reference materials?

This repository does not contain firmware.  It only contains a sample receiver application.  We do not offer Cast firmware to the public as far as I know.
