### ISSUE TITLE
HLS with surround sound (5.1) does not work for me.  

### ISSUE THREAD

**Issue by raestrada95** [googlecast/CastReceiver#7]
Hello.
I have a CAF configured, I can change the audio track but when I select an audio track with 5.1 sound, it changes to that track but the receiver does not change to 5.1. Someone can tell me if it requires any extra configuration that tells you to change to 6 channels.

Thx!.

**Comment by anjaneesh** [comment]
Hello , what kind of stream you are using here? If it is HLS, can you please file a bug using the Cast issue tracker : https://developers.google.com/cast/support#report_issues

**Comment by raestrada95** [comment]
I just saw that Chromecasts no longer work with AAC 5.1 audio, is that correct? . When I create an MPD with ac3 5.1 it works perfectly the passthrough, but when I do the same in HLS it does not work, why does it happen?.   You could publish an example of HLS with AC3 that is able to play on Chromecast ?. 

Thx.
