### ISSUE TITLE
Switching from Media element to another media element

### ISSUE THREAD

**Issue by ShaimaaHamdan** [googlecast/CastReceiver#8]
Hello ,

I am developing Chrome Cast Receiver App that casting normal videos and Youtube videos with custome code , loading youtube video working fine but once i switch to another player nothing work it keeps dely loading the veido segments
I use the following to set the media element  for the youtube videos
 playerManager.setMediaElement(yt_video_fake);
and for normal video i use this 
playerManager.setMediaElement(document.getElementById('cast-player'));

the problem happen when switching from youtube video to non youtube I got the following errors

![image](https://user-images.githubusercontent.com/8478773/58014869-21439280-7afa-11e9-8e00-f02653141242.png)
![image](https://user-images.githubusercontent.com/8478773/58014969-5b149900-7afa-11e9-84f2-d7ba182b788a.png)

any help ?

**Comment by IMSherrill** [comment]
@ShaimaaHamdan Did you ever solve this issue? I am trying to use the media player with my own `audio` element and am experiencing similar issues. can you upload some sample code of using `setMediaElement`?

**Comment by jtromo** [comment]
The PlayerManager.setMediaElement is designed to set the media element on the page when you have a <video> or <audio> as opposed to using the <cast-media-player>. 

We don't support switching between content in CAF's players and Youtube.
