### ISSUE TITLE
Sample for googlecast-v2 custom receiver code

### ISSUE THREAD

**Issue by srikanthsunkari** [googlecast/CastReceiver#9]
Hi, I am looking for sample code of custom receiver of v2 SDK, [this](https://github.com/googlecast/Cast-Player-Sample) doesn't seem to be working. Since we are on v2 SDK we need a reference for the example to check few things. Can you please help me in finding this?

**Comment by jtromo** [comment]
The sample code for a V2 based receiver has been permanently removed with the deprecation of the v2 libraries. Please reference the migration guide to migrate your receiver to CAF: https://developers.google.com/cast/docs/migrate_v2/receiver
